server:
  port: 8080                #配置程序端口，默认为8080
  session-timeout: 1800   #配置session超时时间，单位为秒
  context-path: /         #默认为/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
