server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/springboot?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123